version: '3.8'

services:
    db:
        image: postgres
        restart: always
        environment:
            - PGDATA=/var/lib/postgresql/data
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"

volumes:
  pg-data:
